import {
  Hotel, Zap, PartyPopper, Heart, Plane, Moon,
  UserCheck, Clock, Backpack, CalendarClock, Baby, Sunset,
} from 'lucide-react'
import eventNanny from "../assets/images/eventnanny.jpg"
import night from "../assets/images/night.jpg"
import travel from "../assets/images/travel-nanny.png"
import full from "../assets/images/full.png"

export const SERVICES = [
  {
    slug: 'hotel-nanny',
    name: 'Hotel Nannies',
    tagline: 'Childcare for guests staying in London hotels',
    icon: Hotel,
    color: '#3A6EA5',
    image: 'https://i.pinimg.com/1200x/f7/51/af/f751af39f275b105e47be6444e83a407.jpg',
    description: 'On-demand, professional childcare for guests staying in London hotels, so parents can relax, work or explore the city with peace of mind.',
    longDescription: 'Visiting London for business, a holiday, or a special occasion? Our hotel nanny service provides professional, DBS-checked childcare directly in your hotel room or suite. Whether you need cover for a business dinner, a West End show, an anniversary, or simply want an adults-only evening while visiting the city, our experienced nannies ensure your children are safe, entertained, and settled for bedtime — even in unfamiliar surroundings.\n\nWe understand hotel-specific logistics: access arrangements, guest policies, lift access with pushchairs, room layouts, and coordinating directly with concierge and guest relations teams. If your hotel requires advance notice or identification for childcare providers, we handle that for you. Simply tell us your hotel, your dates, the number and ages of your children, and any special requirements — we do the rest.',
    whoFor: 'Families visiting London and staying in hotels, serviced apartments, or Airbnbs who need trusted childcare. Also used by concierge teams and travel planners arranging care on behalf of guests.',
    seoTitle: 'Hotel Nanny London | Marvza Private Nannies & Mannies',
    seoDescription: 'Book a professional hotel nanny in London. On-demand, experienced childcare for guests staying in London hotels with Marvza.',
    h1Title: 'Trusted Hotel Nannies in London',
    heroParagraph: 'Professional, on-demand childcare across London hotels for guests, business travellers, and families needing in-room care.',
    primaryCTA: 'Book a Hotel Nanny',
    benefits: [
      'Available at short notice across London hotels',
      'Fully vetted, experienced nannies',
      'Flexible bookings by the hour or for your full stay',
      'Discreet, professional in-room care',
      'Can liaise directly with hotel concierge',
    ],
    faqs: [
      {
        question: 'Can you provide childcare on the same day I check in?',
        answer: 'In most cases, yes — subject to availability. We recommend booking as early as possible, but we do accept short-notice hotel bookings.',
      },
      {
        question: 'Do you work directly with hotel concierge teams?',
        answer: 'Yes. We regularly coordinate with concierge and guest relations teams across London hotels to arrange childcare for guests.',
      },
      {
        question: 'What information do you need to arrange hotel childcare?',
        answer: 'We need your hotel name and address, check-in/check-out dates, the dates and times you need care, the number and ages of your children, and any special requirements (allergies, routines, etc). We will handle any coordination with the hotel directly.',
      },
      {
        question: 'What ages do you support for hotel care?',
        answer: 'Our nannies care for children of all ages, from newborns to teenagers. We ensure you are matched with a nanny whose experience fits your children’s ages.',
      },
    ],
  },
  {
    slug: 'backup-emergency-nanny',
    name: 'Backup & Emergency Nannies',
    tagline: 'Same-day cover when your regular nanny is unavailable',
    icon: Zap,
    color: '#B94A48',
    image: 'https://i.pinimg.com/736x/ad/fc/f0/adfcf0d8aea72100a9b77300cd1a62f8.jpg',
    description: `Same-day and short-notice childcare cover when your family's regular nanny is off sick, on leave, or otherwise unavailable.`,
    longDescription: 'When childcare falls through, you need help fast — not a lengthy registration process. Marvza provides immediate, same-day emergency childcare for London families when plans change unexpectedly.\n\nCommon situations we cover:\n• Your regular nanny calls in sick\n• Nursery or school closes unexpectedly\n• An urgent work meeting or deadline comes up\n• Your usual childcare arrangement is cancelled last-minute\n• A family emergency requires you to be somewhere else\n• You need cover during a gap between permanent nannies\n\nAll our emergency nannies have completed the same rigorous screening process as our permanent placements — enhanced DBS, verified references, paediatric first aid, and face-to-face interviews. We aim to have a trusted, experienced professional at your door as quickly as possible so your day can continue.',
    whoFor: 'Any London family whose regular childcare has fallen through and needs reliable, vetted cover at short notice — whether for a single day or a short run of days.',
    seoTitle: 'Emergency Nanny & Backup Childcare London | Marvza',
    seoDescription: 'Need childcare today? Book an experienced emergency nanny in London for same-day and short-notice backup childcare with Marvza.',
    h1Title: 'Emergency & Backup Nannies in London',
    heroParagraph: 'Same-day and short-notice childcare across London when your regular nanny is unavailable or plans change unexpectedly.',
    primaryCTA: 'Request Emergency Childcare',
    benefits: [
      'Available at short notice, including same-day',
      'Experienced, thoroughly vetted professionals',
      'Flexible single days or short runs of cover',
      'No long-term commitment required',
      'Consistent quality of care under pressure',
    ],
    faqs: [
      {
        question: 'How quickly can a backup or emergency nanny be arranged?',
        answer: 'We aim to place cover as quickly as possible, including same-day where availability allows. The sooner you contact us, the more options we can offer.',
      },
      {
        question: 'Is there a minimum booking length?',
        answer: 'No — backup and emergency cover can be booked for a single day or repeated as needed.',
      },
      {
        question: 'What if my nursery closes unexpectedly?',
        answer: 'This is one of the most common reasons families contact us. Call or WhatsApp us as soon as you know, and we will work to arrange cover for the same day.',
      },
      {
        question: 'Are emergency nannies vetted to the same standard?',
        answer: 'Absolutely. Every nanny in our emergency pool has completed the same rigorous screening as our permanent placements, including enhanced DBS checks, verified references, and paediatric first aid certification.',
      },
    ],
  },
  {
    slug: 'event-nanny',
    name: 'Event Nannies',
    tagline: 'Childcare for corporate events, parties and productions',
    icon: PartyPopper,
    color: '#B98945',
    image: eventNanny,
    description: 'Professional childcare for corporate events, parties, private functions and productions — so children are safe and entertained while everyone else enjoys the occasion.',
    longDescription: 'Make your special day stress-free for both you and your guests. From civil ceremonies and wedding receptions to large corporate events and private parties, our event nannies provide dedicated childcare and entertainment. We can set up a supervised children’s area, coordinate meals, arrange engaging activities, and manage the bedtime routine for younger guests, ensuring the adults can fully participate in the celebration.',
    whoFor: 'Event organisers, corporate teams, and families hosting parties or functions where children will be present.',
    seoTitle: 'Event Nanny London | Corporate & Private Childcare | Marvza',
    seoDescription: 'Hire professional event nannies in London for corporate events, parties, and productions. Safe, engaging childcare with Marvza.',
    h1Title: 'Professional Event Nannies in London',
    heroParagraph: 'Dedicated childcare for corporate events, private parties, and productions across London, ensuring children are safe and entertained.',
    primaryCTA: 'Book Event Nannies',
    benefits: [
      'Experienced with group and one-to-one childcare',
      'Engaging, age-appropriate activities',
      'Safe, supervised environment throughout your event',
      'Scales from small gatherings to larger productions',
      'Allows parents and organisers to be fully present',
    ],
    faqs: [
      {
        question: 'How many nannies do we need for our event?',
        answer: 'This depends on the number and ages of children attending. As a guide, we recommend at least one nanny per four children.',
      },
      {
        question: `Can you staff a dedicated children's area at our event?`,
        answer: 'Yes — we can set up and run a supervised children\'s area for the duration of your event.',
      },
    ],
  },
  {
    slug: 'wedding-nanny',
    name: 'Wedding Nannies',
    tagline: `Individual care or a staffed children's area for your big day`,
    icon: Heart,
    color: '#9C7048',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop',
    description: `Individual childcare or a fully staffed children's area during weddings, so parents and guests can celebrate without worry.`,
    longDescription: `Weddings bring families together — including the youngest guests. Our wedding nannies provide individual, one-to-one care or run a dedicated, supervised children's area for the day, keeping little ones happy and entertained while the celebration continues.`,
    whoFor: 'Couples and wedding planners who want children looked after — individually or as a group — throughout the ceremony and reception.',
    seoTitle: 'Wedding Nanny London | Wedding Childcare Services | Marvza',
    seoDescription: 'Book experienced wedding nannies in London. We provide individual care or a fully staffed children\'s area for your big day.',
    h1Title: 'Trusted Wedding Nannies in London',
    heroParagraph: 'Individual care or fully staffed children\'s areas for weddings across London and surrounding areas, letting parents enjoy the celebration.',
    primaryCTA: 'Book a Wedding Nanny',
    benefits: [
      'One-to-one or group childcare on the day',
      `Dedicated, supervised children's area available`,
      'Experienced with formal and all-day events',
      `Coordinated closely with your wedding planner`,
      'Lets parents and guests fully enjoy the day',
    ],
    faqs: [
      {
        question: 'Can nannies cover the ceremony and reception?',
        answer: 'Yes — we can arrange cover for the ceremony only, the reception only, or the full day.',
      },
      {
        question: 'Do you liaise with our wedding planner or venue?',
        answer: `Yes, we're happy to coordinate directly with your planner or venue to fit around your day's schedule.`,
      },
    ],
  },
  {
    slug: 'travel-vacation-nanny',
    name: 'Travel & Vacation Nannies',
    tagline: 'UK and international travel with your family',
    icon: Plane,
    color: '#3F7656',
    image: travel,
    description: 'Experienced nannies who travel with your family across the UK and internationally, providing continuity of care wherever you go.',
    longDescription: `Travelling with children — for a family holiday, a work trip, or an extended stay abroad — is easier with the right support. Our travel and vacation nannies join your family for the duration of the trip, providing familiar, consistent care in a new environment.`,
    whoFor: 'Families travelling within the UK or abroad who want continuity of childcare while away from home.',
    seoTitle: 'Travel & Vacation Nanny London | Holiday Childcare | Marvza',
    seoDescription: 'Hire a travel nanny for UK and international family holidays. Consistent, experienced childcare away from home with Marvza.',
    h1Title: 'Experienced Travel & Vacation Nannies',
    heroParagraph: 'Professional nannies travelling with your family across the UK or internationally, providing continuity of care wherever you go.',
    primaryCTA: 'Request a Travel Nanny',
    benefits: [
      'Experienced travelling with families internationally',
      'Continuity of care away from home',
      'Flexible to holiday and travel itineraries',
      'Can support with jet lag, routines and time zones',
      'Frees parents to relax or work while travelling',
    ],
    faqs: [
      {
        question: 'Do travel nannies need a visa or work permit?',
        answer: `This depends on the destination. We'll discuss the requirements for your specific trip and help you plan accordingly.`,
      },
      {
        question: 'Who covers travel costs and accommodation?',
        answer: 'Typically the family covers travel, accommodation and expenses for the nanny during the trip — full details are agreed before you travel.',
      },
    ],
  },
  {
    slug: 'night-nanny',
    name: 'Night Nannies',
    tagline: 'Overnight support, particularly for babies and young children',
    icon: Moon,
    color: '#2A1B17',
    image: night,
    description: 'Overnight childcare support for babies, toddlers, and young children, so parents can get the rest they need.',
    longDescription: `A night nanny provides experienced overnight childcare — typically covering from late evening through to early morning — so parents can sleep. Unlike a maternity nanny (who specialises in newborn-specific postnatal care), a night nanny is suitable for children of various ages who need overnight support, whether that's a baby who hasn't yet established a sleep routine, a toddler going through a difficult phase, or a young child recovering from illness.\n\nOur night nannies manage feeds, nappy changes, settling, and soothing throughout the night. Many also have experience supporting gentle sleep-training approaches, though always guided by your family's preferences. Night nannies can be booked for single nights, a regular weekly pattern, or a focused block of nights to help establish better sleep.`,
    whoFor: 'Families with babies, toddlers, or young children who need experienced overnight support — whether for sleep training, rest recovery, or ongoing nighttime care.',
    seoTitle: 'Night Nanny London | Overnight Newborn Support | Marvza',
    seoDescription: 'Book an experienced night nanny in London. Specialist overnight childcare and sleep support for babies and young children.',
    h1Title: 'Trusted Night Nannies in London',
    heroParagraph: 'Specialist overnight support for families across London, helping with feeding, settling, and sleep routines so parents can rest.',
    primaryCTA: 'Book a Night Nanny',
    benefits: [
      'Specialist experience with babies and young children',
      'Supports feeding, settling and night routines',
      'Allows parents uninterrupted rest',
      'Available for single nights or ongoing support',
      'Can support with sleep training approaches',
    ],
    faqs: [
      {
        question: 'What hours does a night nanny typically cover?',
        answer: 'Night nannies typically cover from evening bedtime through to early morning, though exact hours are agreed with your nanny.',
      },
      {
        question: 'Can a night nanny help with sleep training?',
        answer: 'Many of our night nannies have experience supporting gentle sleep training approaches — let us know your preferences when enquiring.',
      },
    ],
  },
  {
    slug: 'full-time-nanny',
    name: 'Full-Time Nannies',
    tagline: 'Permanent, live-in or live-out placements',
    icon: UserCheck,
    color: '#3B2923',
    image: full,
    description: 'A dedicated nanny working regular hours as part of your household, on a live-in or live-out basis — the gold standard in personalised childcare.',
    longDescription: `A full-time nanny becomes an integral part of your family life, providing consistent, personalised care tailored to your children's routines and development. Placements can be arranged live-in or live-out, depending on what suits your household best.`,
    whoFor: 'Families with children of any age who need consistent, high-quality care throughout the working week, on a permanent basis.',
    seoTitle: 'Full-Time Nanny London | Live-in & Live-out | Marvza',
    seoDescription: 'Find the perfect full-time nanny in London. Rigorously vetted live-in or live-out nannies for permanent placements with Marvza.',
    h1Title: 'Professional Full-Time Nannies in London',
    heroParagraph: 'Dedicated, permanent childcare for your family. We match you with experienced live-in or live-out nannies across London.',
    primaryCTA: 'Find a Full-Time Nanny',
    benefits: [
      'Consistent one-to-one care',
      'Live-in or live-out arrangements available',
      'Child-led routines and activities',
      'School and nursery runs',
      'Light household duties related to the children',
      'Continuity of care and strong bonding',
    ],
    faqs: [
      {
        question: 'What hours does a full-time nanny typically work?',
        answer: 'Full-time nannies typically work between 40–50 hours per week, though this is agreed between you and your nanny directly.',
      },
      {
        question: 'Should we choose live-in or live-out?',
        answer: `This depends on your household's space, routine and need for flexibility. We'll talk through both options during matching.`,
      },
    ],
  },
  {
    slug: 'part-time-nanny',
    name: 'Part-Time Nannies',
    tagline: 'Recurring care for fewer hours or days',
    icon: Clock,
    color: '#A8927E',
    image: 'https://i.pinimg.com/1200x/cf/18/04/cf180417e888630cc8e4a26d83b7c245.jpg',
    description: 'Recurring, part-time childcare for families who need fewer hours or days each week rather than full-time cover.',
    longDescription: `Not every family needs a nanny five days a week. Our part-time nannies provide reliable, recurring care on the specific days and hours that suit your household — whether that's a couple of mornings a week or set days around your work schedule.`,
    whoFor: 'Families who need regular but reduced-hours childcare, such as a few days or mornings each week.',
    seoTitle: 'Part-Time Nanny London | Flexible Childcare | Marvza',
    seoDescription: 'Hire a part-time nanny in London for recurring weekly childcare. Flexible, reliable support for your family\'s schedule.',
    h1Title: 'Reliable Part-Time Nannies in London',
    heroParagraph: 'Recurring, dependable childcare for families across London who need flexible support for fewer hours or specific days each week.',
    primaryCTA: 'Find a Part-Time Nanny',
    benefits: [
      'Recurring, dependable weekly schedule',
      'Flexible to the specific days and hours you need',
      'Consistent carer for your children each week',
      'More affordable than full-time cover',
      'Easily combined with nursery or school hours',
    ],
    faqs: [
      {
        question: `What's the minimum commitment for part-time care?`,
        answer: 'We typically look for a regular weekly pattern, even if it\'s just one or two sessions, so your nanny can build routine with your children.',
      },
      {
        question: 'Can part-time hours change from week to week?',
        answer: 'Some flexibility is possible, but part-time nannies generally work best with a consistent, agreed schedule.',
      },
    ],
  },
  {
    slug: 'after-school-nanny',
    name: 'After-School Nannies',
    tagline: 'Collection, activities, meals and evening routines',
    icon: Backpack,
    color: '#B88A62',
    image: 'https://i.pinimg.com/736x/f2/83/c0/f283c008dbbb6fd0ad70d260b6f34fc8.jpg',
    description: 'Reliable after-school support covering school collection, activities, meals and the evening routine until parents are home.',
    longDescription: `The after-school hours can be some of the busiest of the day. Our after-school nannies collect your children from school or activities, help with homework, prepare meals and manage the evening routine — bridging the gap until you're home.`,
    whoFor: `Working families who need consistent support from school pick-up through to bedtime or parents' return home.`,
    seoTitle: 'After-School Nanny London | Pick-ups & Care | Marvza',
    seoDescription: 'Book a reliable after-school nanny in London for school collections, homework help, and evening routines with Marvza.',
    h1Title: 'Trusted After-School Nannies in London',
    heroParagraph: 'Reliable afternoon support across London, bridging the gap between the school run and the end of your working day.',
    primaryCTA: 'Book an After-School Nanny',
    benefits: [
      'School and activity collection',
      'Homework support',
      'Meal preparation for children',
      'Bath and bedtime routines where needed',
      'Consistent, familiar carer each afternoon',
    ],
    faqs: [
      {
        question: 'Can an after-school nanny collect from multiple schools or activities?',
        answer: 'Yes, we can match you with a nanny able to manage school and activity collections for multiple children.',
      },
      {
        question: 'Do after-school nannies drive?',
        answer: `Many do — let us know if a driving licence and car access are important for your family, and we'll match accordingly.`,
      },
    ],
  },
  {
    slug: 'temporary-adhoc-nanny',
    name: 'Temporary & Ad-Hoc Nannies',
    tagline: 'One day, several days or several weeks',
    icon: CalendarClock,
    color: '#5A4238',
    image: 'https://i.pinimg.com/1200x/08/a9/8e/08a98ebae4418ad604a84fa51abcc7f7.jpg',
    description: 'Flexible temporary childcare for one day, several days or several weeks — without a long-term commitment.',
    longDescription: `Sometimes you need childcare for a defined period rather than an ongoing arrangement — covering a house move, a busy work project, or a gap between other care. Our temporary and ad-hoc nannies provide experienced, reliable cover for exactly the period you need.`,
    whoFor: 'Families who need short-term or one-off childcare cover without committing to a permanent placement.',
    seoTitle: 'Temporary Nanny London | Ad-Hoc Childcare | Marvza',
    seoDescription: 'Hire a temporary nanny in London. Flexible ad-hoc childcare for a day, a week, or a month with no long-term commitment.',
    h1Title: 'Temporary & Ad-Hoc Nannies in London',
    heroParagraph: 'Flexible, short-term childcare cover across London for one-off gaps, busy periods, or transition times between permanent care.',
    primaryCTA: 'Book a Temporary Nanny',
    benefits: [
      'Flexible from a single day to several weeks',
      'No long-term commitment required',
      'Experienced, fully vetted professionals',
      'Quick to arrange for planned or unplanned gaps',
      'Can be repeated whenever the need arises',
    ],
    faqs: [
      {
        question: 'How far in advance should we book temporary cover?',
        answer: 'As far in advance as possible for the best availability, though we do accommodate shorter-notice requests where we can.',
      },
      {
        question: 'Can temporary cover turn into an ongoing arrangement?',
        answer: `Yes — if it's a good fit, many temporary placements can be extended or transitioned into a part-time or full-time arrangement.`,
      },
    ],
  },
  {
    slug: 'maternity-newborn-nanny',
    name: 'Maternity/Newborn Nannies',
    tagline: 'Specialist newborn and postnatal support',
    icon: Baby,
    color: '#7C6659',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=1200&auto=format&fit=crop',
    description: 'Experienced postnatal support for new parents, helping with feeding, settling, and establishing early routines during the newborn period.',
    longDescription: `A maternity nanny provides specialist, hands-on support during the postnatal period — typically from birth through the first few months. This is a distinct service from a general night nanny: maternity nannies have specific experience with newborns and the unique challenges of the early weeks, including breastfeeding support, bottle-feeding routines, winding, reflux management, cord care, and helping parents build confidence with their new baby.\n\nOur maternity nannies work on a daytime, overnight, or 24-hour live-in basis depending on your family's needs. They focus on establishing sustainable feeding and sleep routines, supporting parental wellbeing, and providing calm, reassuring guidance during what can be an overwhelming time. Please note: our maternity nannies are experienced childcare professionals with specialist newborn training, not registered midwives or health visitors. For medical concerns, we always recommend consulting your midwife or GP.`,
    whoFor: 'New and expectant parents who want experienced, hands-on postnatal support specifically during the newborn period (typically birth to 3-4 months).',
    seoTitle: 'Maternity Nanny London | Newborn Care | Marvza',
    seoDescription: 'Hire a maternity nanny in London for specialist newborn care, postnatal support, and early routine establishment with Marvza.',
    h1Title: 'Specialist Maternity & Newborn Nannies',
    heroParagraph: 'Expert postnatal support for new parents across London, focusing on newborn care, feeding, and helping families adjust.',
    primaryCTA: 'Book a Maternity Nanny',
    benefits: [
      'Specialist newborn care experience',
      'Support with feeding and settling',
      'Guidance establishing early routines',
      'Reassurance and support for new parents',
      'Available on a daytime, overnight or live-in basis',
    ],
    faqs: [
      {
        question: 'When should we book a maternity nanny?',
        answer: 'Many families book during pregnancy to secure the right match, with the nanny starting shortly after the baby arrives.',
      },
      {
        question: 'Can a maternity nanny support multiples?',
        answer: 'Yes, several of our maternity nannies have specific experience supporting families with twins or multiples.',
      },
    ],
  },
  {
    slug: 'evening-babysitter',
    name: 'Evening Babysitters',
    tagline: 'Evening and late-night bookings',
    icon: Sunset,
    color: '#3B2923',
    image: 'https://i.pinimg.com/1200x/eb/af/3d/ebaf3d6c31ede0ae929f079bdb198a89.jpg',
    description: 'Trusted evening and late-night babysitting for date nights, dinners, theatre, work events, hotel stays, and short-notice plans.',
    longDescription: `Our evening babysitters provide professional, fully vetted childcare for parents who want to enjoy an evening out — or simply need a few hours to themselves. Every babysitter we send has completed the same rigorous screening as our permanent nanny placements.\n\nCommon situations we cover:\n• Date nights and anniversary dinners\n• West End shows, concerts, and theatre\n• Corporate events and work dinners\n• Wedding receptions and private parties\n• Hotel stays (we send babysitters directly to London hotels)\n• Last-minute or short-notice evening plans\n• Late-night cover when you need to stay out past midnight\n\nOur babysitters arrive in time for you to do a handover, manage the bedtime routine if needed, and stay as late as you require. We simply ask that you arrange a safe journey home for late finishes.`,
    whoFor: 'London families who need occasional or one-off evening childcare — whether planned in advance or at short notice.',
    seoTitle: 'Evening Babysitter London | Marvza Private Nannies & Mannies',
    seoDescription: 'Book an experienced evening babysitter in London for date nights, dinners, events, hotel stays and short-notice childcare with Marvza.',
    h1Title: 'Trusted Evening Babysitters in London',
    heroParagraph: 'Professional evening childcare across London for date nights, dinners, events, work commitments, hotel stays and last-minute plans.',
    primaryCTA: 'Book an Evening Babysitter',
    benefits: [
      'Available for evening and late-night bookings',
      'Same vetting standards as our nanny placements',
      'Ideal for occasional or one-off evenings out',
      'Flexible, short-notice bookings where possible',
      'Familiar routine handover for bedtime',
    ],
    faqs: [
      {
        question: 'How late can a babysitter stay?',
        answer: 'Our babysitters can stay as late as you need. Many families book cover until after midnight. If finishing very late, we simply ask that a safe journey home (such as a taxi) is provided or covered.',
      },
      {
        question: 'Can I book at short notice?',
        answer: 'Yes, we specialize in providing trusted evening cover at short notice, though we recommend booking early for busy weekends.',
      },
      {
        question: 'Can you provide a babysitter to a hotel?',
        answer: 'Absolutely. We frequently provide evening babysitters to families staying in hotels across London.',
      },
      {
        question: 'What ages do you support?',
        answer: 'We cover all ages from newborns to teenagers. We ensure the babysitter we send has specific experience with your children’s age group.',
      },
      {
        question: 'How are babysitters screened?',
        answer: 'All babysitters go through the exact same rigorous screening process as our permanent nannies, including enhanced DBS checks, verified references, and paediatric first aid certification.',
      },
    ],
  },
]

export function getServiceBySlug(slug) {
  return SERVICES.find(s => s.slug === slug)
}
